### ISSUE TITLE
MP4 chunck question

### ISSUE THREAD

**Issue by sonnyk22** [aroirocks/VideoClient#1]
To start, excellent multi-part articles, and great app on the github.

I wish the demo link was working correctly.  

Quick question; after concatenating a multiple MP4 chunks into a single file, and then processing it via the `ffmpeg`,  **did you run into any issue(s)**, such as the first part (first chunk) of the file plays until the end, but only to see a frozen picture at the end of chunk 1?

In my local web application, I am not using `ResumableJS` to upload chunks, however, I am uploading each chunks by first converting them from blob to `'base64' (new FileReader())` on the client, and then on the server, saving each (converted back to blob) as a MP4 chunks in Azure, and finally apply the `ffmpeg` on the full merged blob file.  This **works great** with all .MOV uploaded files without 'any frozen parts' when playback, but not sure why it does not work with MP4.   Is there an extra I am missing when dealing with MP4?

Thank you

**Comment by aroirocks** [comment]
Hi, @sonnyk22  No I didn't run into any sort of such issues as resumable Js uses HTML 5 API I am unaware of the granular details also its takes care for me the uploading & merging of files and exposes a few functions which help me monitor the data uploaded also its working perfectly fine with Mp4 Files.

Apologies for the demo the bill was huge to keep the server up & running. :)
